'use client';
import {useState,useEffect} from 'react';
import type {Content} from '@/lib/content';
import {Picture} from '@/app/public-site';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Switch} from '@/components/ui/switch';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogAction,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {Toaster,toast} from 'sonner';
import {Save,Plus,Trash2,Upload,ExternalLink,LogOut} from 'lucide-react';
const tabs=[['home','Inicio'],['services','Servicios'],['products','Productos'],['about','Nosotros'],['process','Proceso'],['reviews','Reseñas'],['gallery','Galería'],['faq','Preguntas frecuentes'],['contact','Contacto'],['footer','Cierre / Footer']];
const labels:Record<string,string>={eyebrow:'Etiqueta superior',title:'Título',description:'Descripción',microcopy:'Texto bajo los botones',subtitle:'Subtítulo',category:'Categoría',quote:'Frase destacada',doctor:'Nombre de la doctora',reasonsTitle:'Título de «Por qué elegirnos»',message:'Mensaje personalizado de WhatsApp',rating:'Calificación de Google',count:'Cantidad de reseñas en Google',invitation:'Invitación a calificar',name:'Nombre',text:'Texto de la reseña',stars:'Estrellas',published:'Visible en el sitio',question:'Pregunta',answer:'Respuesta',intro:'Texto introductorio',address:'Dirección',city:'Ciudad',phone:'Teléfono visible',whatsapp:'WhatsApp visible',hours:'Horarios',mapEmbed:'URL del mapa embebido',requestTitle:'Título de solicitud rápida',requestDescription:'Descripción de solicitud rápida',phoneUrl:'URL de teléfono',whatsappUrl:'URL de WhatsApp',facebookUrl:'URL de Facebook',instagramUrl:'URL de Instagram',mapsUrl:'URL de Google Maps',agendaUrl:'URL de AgendaPro',reviewsUrl:'URL de reseñas de Google',corporate:'Descripción corporativa del footer',alt:'Texto alternativo de la imagen'};
const clone=<T,>(v:T):T=>JSON.parse(JSON.stringify(v));
export default function Editor({initial,logout}:{initial:Content,logout:string}){const[draft,setDraft]=useState(initial),[saved,setSaved]=useState(initial),[busy,setBusy]=useState(false),[uploads,setUploads]=useState(0),[dialog,setDialog]=useState<{title:string,description:string,run:()=>void}|null>(null);const dirty=JSON.stringify(draft)!==JSON.stringify(saved);
useEffect(()=>{if(!dirty&&!uploads)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty,uploads]);
function set(path:(string|number)[],value:unknown){setDraft(prev=>{const c=clone(prev);let n:any=c;for(const k of path.slice(0,-1))n=n[k];n[path[path.length-1]]=value;return c})}
async function save(){setBusy(true);try{const r=await fetch('/api/admin/site-content',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)});const d=await r.json();if(!r.ok)throw Error(d.error||'No se pudo guardar');setSaved(clone(draft));toast.success('Cambios guardados',{description:'El contenido del sitio ha sido actualizado exitosamente.'})}catch(e){toast.error(e instanceof Error?e.message:'No se pudo guardar')}finally{setBusy(false)}}
function leave(url:string){if(dirty||uploads)setDialog({title:'¿Salir sin guardar?',description:'Los cambios pendientes no aparecerán en el sitio.',run:()=>{window.location.href=url}});else window.location.href=url}
function fields(value:any,path:(string|number)[]):React.ReactNode{return Object.entries(value).map(([key,v])=>{const p=[...path,key],id=p.join('-');if(key==='image')return <Photo key={id} value={v as any} path={p} set={set} uploadChange={n=>setUploads(x=>x+n)} title={path[0]==='home'?'Imagen principal':'Imagen del equipo'}/>;
if(Array.isArray(v)){if(key==='images')return <div className="admin-gallery" key={id}>{v.map((photo,i)=><Photo key={i} value={photo} path={[...p,i]} set={set} uploadChange={n=>setUploads(x=>x+n)} title={`Foto ${i+1}`} action={i<6?'Cambiar imagen':'Añadir foto'}/>)}</div>;const type=path[0]==='services'?'servicio':path[0]==='products'?'producto':path[0]==='process'?'paso':path[0]==='reviews'?'reseña':path[0]==='faq'?'pregunta':'razón';const blank=path[0]==='reviews'?{name:'',text:'',stars:5,published:false}:path[0]==='faq'?{question:'',answer:'',published:false}:path[0]==='services'?{category:'',title:'',description:'',message:''}:{title:'',description:''};return <div key={id} className="admin-items">{v.map((item,i)=><article className="admin-item" key={i}><div className="admin-item-top"><h3>{type.charAt(0).toUpperCase()+type.slice(1)} {i+1}</h3>{key!=='reasons'&&<button type="button" className="delete-button" onClick={()=>setDialog({title:`¿Eliminar ${type}?`,description:'Podrás descartar los cambios antes de guardarlos.',run:()=>set(p,v.filter((_,j)=>j!==i))})}><Trash2 size={17}/>Eliminar</button>}</div><div className="editor-fields">{fields(item,[...p,i])}</div></article>)}{key!=='reasons'&&<button className="button outline" type="button" onClick={()=>set(p,[...v,blank])}><Plus size={17}/>Añadir {type}</button>}</div>}
if(typeof v==='boolean')return <label className="switch-field" key={id} htmlFor={id}><Switch id={id} checked={v} onCheckedChange={b=>set(p,b)}/>{labels[key]}</label>;
if(key==='stars')return <label className="editor-field" key={id}>{labels[key]}<Select value={String(v)} onValueChange={s=>set(p,Number(s))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{[1,2,3,4,5].map(x=><SelectItem key={x} value={String(x)}>{x} estrella{x>1?'s':''}</SelectItem>)}</SelectContent></Select></label>;
const long=['description','text','answer','hours','corporate','message','requestDescription','quote','subtitle','intro'].includes(key);return <label className={'editor-field '+(long?'full':'')} key={id} htmlFor={id}>{labels[key]||key}{typeof v==='number'?<input id={id} type="number" value={v} min="0" max={key==='rating'?5:undefined} step={key==='rating'?'.1':'1'} onChange={e=>set(p,Number(e.target.value))}/>:long?<textarea id={id} rows={key==='description'&&path[0]==='about'?7:3} value={String(v)} onChange={e=>set(p,e.target.value)}/>:<input id={id} value={String(v)} onChange={e=>set(p,e.target.value)}/>}</label>})}
return <main className="admin-shell"><Toaster richColors/><header className="admin-header"><div><a className="admin-brand" href="/" onClick={e=>{e.preventDefault();leave('/')}}>NanyVet <span>Admin</span></a><p>{dirty?'Cambios sin guardar':'Contenido actualizado'}</p></div><div className="admin-actions"><a href="/" target="_blank" rel="noopener noreferrer" className="button outline"><ExternalLink size={16}/>Ver sitio</a><button className="button outline" onClick={()=>leave(logout)}><LogOut size={16}/>Salir</button><button className="button outline" disabled={!dirty||busy||!!uploads} onClick={()=>setDialog({title:'¿Descartar los cambios?',description:'Se restaurará el último contenido guardado.',run:()=>setDraft(clone(saved))})}>Descartar</button><button className="button" disabled={!dirty||busy||!!uploads} onClick={save}><Save size={16}/>{busy?'Guardando…':uploads?'Subiendo imagen…':'Guardar cambios'}</button></div></header><div className="admin-body"><h1>El cuidado también está en los detalles.</h1><p>Edita los textos y las imágenes de tu clínica. Guarda los cambios para publicarlos en el sitio.</p><Tabs defaultValue="home"><TabsList className="admin-tabs-list">{tabs.map(([id,l])=><TabsTrigger key={id} value={id}>{l}</TabsTrigger>)}</TabsList>{tabs.map(([id,l])=><TabsContent key={id} value={id}><section className="admin-panel"><div className="admin-panel-heading"><span>Contenido del sitio</span><h2>{l}</h2>{id==='reviews'&&<p>La calificación y las reseñas se actualizan manualmente. Solo se muestran las reseñas publicadas.</p>}{id==='gallery'&&<p>Once posiciones para tus fotos, seguidas de Instagram. Las posiciones vacías se muestran como marcos suaves.</p>}</div><fieldset disabled={busy} className="editor-fields">{fields(draft[id as keyof Content],[id])}</fieldset></section></TabsContent>)}</Tabs></div><AlertDialog open={!!dialog} onOpenChange={open=>!open&&setDialog(null)}><AlertDialogContent><AlertDialogTitle>{dialog?.title}</AlertDialogTitle><AlertDialogDescription>{dialog?.description}</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction onClick={()=>{dialog?.run();setDialog(null)}}>Confirmar</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></main>}
function Photo({value,path,set,uploadChange,title,action}:{value:{src:string,alt:string},path:(string|number)[],set:(p:(string|number)[],v:unknown)=>void,uploadChange:(n:number)=>void,title:string,action?:string}){const[preview,setPreview]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);async function upload(file?:File){if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10485760){toast.error('Selecciona JPEG, PNG o WebP de hasta 10 MB.');return}setPreview(URL.createObjectURL(file));setBusy(true);uploadChange(1);try{const r=await fetch('/api/storage/uploads/request-url',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:file.type,size:file.size})});const d=await r.json();if(!r.ok)throw Error(d.error);const result=await fetch(d.uploadUrl,{method:d.method,headers:{'Content-Type':file.type},body:file});if(!result.ok)throw Error('No se pudo subir la imagen. Inténtalo otra vez.');set([...path,'src'],d.url);toast.success('Imagen cargada. Guarda los cambios para publicarla.')}catch(e){toast.error(e instanceof Error?e.message:'Error al subir')}finally{setPreview('');setBusy(false);uploadChange(-1)}}return <div className="photo-editor"><h3>{title}</h3><Picture src={preview||value.src} alt={value.alt}/><label className="button outline upload-label"><Upload size={16}/>{busy?'Subiendo…':action||(value.src?'Cambiar imagen':'Añadir foto')}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{upload(e.target.files?.[0]);e.target.value=''}}/></label><small>JPEG, PNG o WebP · Máximo 10 MB</small><label>Texto alternativo<input value={value.alt} onChange={e=>set([...path,'alt'],e.target.value)}/></label>{value.src&&<button type="button" className="delete-button" disabled={busy} onClick={()=>set([...path,'src'],'')}>Quitar imagen</button>}</div>}
