'use client';
import {useState,useEffect,FormEvent} from 'react';
import {ArrowRight,MapPin,Clock,MessageCircle,Menu,X,Phone} from 'lucide-react';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import type {Content} from '@/lib/content';
function Instagram({size=24}:{size?:number}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r=".8" fill="currentColor" stroke="none"/></svg>}
function Facebook({size=24}:{size?:number}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M14 22v-9h3l.5-4H14V7c0-1 .3-2 2-2h2V1.5c-.5-.1-1.7-.3-3-.3-3 0-5 1.8-5 5V9H7v4h3v9z"/></svg>}
const nav=[['Servicios','servicios'],['Nosotros','nosotros'],['Comunidad','comunidad'],['Contacto','contacto']];
export function Picture({src,alt}:{src:string,alt:string}){const[bad,setBad]=useState(false);useEffect(()=>setBad(false),[src]);return src&&!bad?<img src={src} alt={alt} loading="lazy" onError={()=>setBad(true)}/>:<div className="photo-empty" role="img" aria-label="Espacio disponible para una fotografía"/>}
function Link({href,children,className='',label}:{href:string,children:React.ReactNode,className?:string,label?:string}){return <a href={href} target="_blank" rel="noopener noreferrer" className={className} aria-label={label}>{children}</a>}
export default function PublicSite({initial}:{initial:Content}){const[c,setC]=useState(initial),[menu,setMenu]=useState(false),[scroll,setScroll]=useState(0),[kind,setKind]=useState(''),[timing,setTiming]=useState(''),[error,setError]=useState('');useEffect(()=>{const run=()=>setScroll(window.scrollY);run();window.addEventListener('scroll',run,{passive:true});fetch('/api/site-content',{cache:'no-store'}).then(r=>r.ok?r.json():null).then(d=>d&&setC(d)).catch(()=>{});return()=>window.removeEventListener('scroll',run)},[]);const t=c.contact,wa=(message?:string)=>t.whatsappUrl+(message?(t.whatsappUrl.includes('?')?'&':'?')+'text='+encodeURIComponent(message):'');const agenda=(s='button')=><Link href={t.agendaUrl} className={s}>Agendar hora <ArrowRight size={16}/></Link>,whats=(s='button outline')=><Link href={wa()} className={s}><MessageCircle size={16}/>Hablar por WhatsApp</Link>;
function send(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),owner=String(f.get('owner')||'').trim(),pet=String(f.get('pet')||'').trim();if(!owner||!pet||!kind||!timing){setError('Completa todos los campos para preparar tu solicitud.');return}setError('');window.open(wa(`Hola NanyVet, soy ${owner}. Quisiera información para mi mascota ${pet}.\nMotivo: ${kind}\nDisponibilidad: ${timing}`),'_blank','noopener,noreferrer')}
return <main><header className={'site-header '+(scroll>30?'scrolled':'')}><div className="wrap header-inner"><a href="#inicio" className="brand">Nany<span>Vet</span><small>Clínica Veterinaria</small></a><nav className="desktop-nav" aria-label="Navegación principal">{nav.map(([l,id])=><a href={'#'+id} key={id}>{l}</a>)}</nav><div className="desktop-actions"><Link href={wa()} className="header-wa"><MessageCircle size={16}/>WhatsApp</Link>{agenda()}</div><button className="mobile-toggle" aria-expanded={menu} aria-label={menu?'Cerrar menú':'Abrir menú'} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div>{menu&&<nav className="mobile-nav">{nav.map(([l,id])=><a href={'#'+id} key={id} onClick={()=>setMenu(false)}>{l}</a>)}{whats()}{agenda()}</nav>}</header>
<section id="inicio" className="wrap hero"><div><p className="eyebrow">{c.home.eyebrow}</p><h1>{c.home.title}</h1><p className="hero-description">{c.home.description}</p><p className="hero-promise">Una veterinaria cercana, con vocación, que escucha, explica y trata a cada mascota con cariño.</p><div className="actions">{agenda()}{whats()}</div><p className="microcopy">{c.home.microcopy}</p></div><div className="hero-visual"><Picture {...c.home.image}/><Link href={wa()} className="floating-note"><span><MessageCircle/></span><div><strong>¿Dudas sobre el servicio?</strong><small>Escríbenos directamente y te orientamos.</small></div></Link></div></section>
<div className="wrap trust"><div><MapPin/><p><strong>Ubicación</strong><span>{t.address}</span></p></div><div><Clock/><p><strong>Atención de lunes a sábado</strong><span>Agenda tu visita con anticipación</span></p></div><div><MessageCircle/><p><strong>Consulta previa</strong><span>Orientación por WhatsApp</span></p></div></div>
<section className="wrap section" id="servicios"><p className="eyebrow">Nuestros servicios</p><h2>{c.services.title}</h2><p className="section-intro">{c.services.subtitle}</p><div className="services-grid">{c.services.items.map((s,i)=><article className="service" key={i}><div className="service-top"><span className="number">{i+1}</span><span className="service-category">{s.category}</span></div><h3>{s.title}</h3><p>{s.description}</p><Link href={wa(s.message)} className="text-link">Consulta disponibilidad <ArrowRight size={15}/></Link></article>)}</div></section>
{c.products.published&&<section className="wrap product-strip" aria-labelledby="productos-title"><div className="product-copy"><p className="eyebrow">{c.products.eyebrow}</p><h2 id="productos-title">{c.products.title}</h2><p>{c.products.description}</p><Link href={wa(c.products.message)} className="text-link pink">Consultar disponibilidad <ArrowRight size={16}/></Link></div><div className="product-list">{c.products.items.map((item,i)=><article key={i}><span>{String(i+1).padStart(2,'0')}</span><div><h3>{item.title}</h3><p>{item.description}</p></div></article>)}</div></section>}
<section className="reasons"><div className="wrap reasons-grid"><h2>{c.about.reasonsTitle}</h2>{c.about.reasons.map((r,i)=><article key={i}><span className="reason-number">0{i+1}</span><h3>{r.title}</h3><p>{r.description}</p></article>)}</div></section>
<section className="wrap section about" id="nosotros"><div className="team-visual"><Picture {...c.about.image}/><div className="doctor-card"><strong>{c.about.doctor}</strong><span>{c.about.quote}</span></div></div><div><p className="eyebrow">El equipo</p><h2>{c.about.title}</h2><p className="preserve">{c.about.description}</p><Link href={t.agendaUrl} className="text-link">Conoce al equipo en tu próxima visita <ArrowRight size={16}/></Link></div></section>
<section className="wrap section process"><div className="section-heading"><h2>{c.process.title}</h2><Link href={wa()} className="text-link pink">Hablar por WhatsApp <ArrowRight size={16}/></Link></div><div className="process-grid">{c.process.items.map((s,i)=><article key={i}><span className="watermark" aria-hidden="true">{i+1}</span><span className="step-index">{String(i+1).padStart(2,'0')}</span><h3>{s.title}</h3><p>{s.description}</p></article>)}</div></section>
<section id="comunidad" className="community"><div className="wrap section reviews-layout"><div><p className="eyebrow">Comunidad NanyVet</p><h2>{c.reviews.title}</h2><p className="section-intro">{c.reviews.subtitle}</p><Link href={t.reviewsUrl} className="google-card"><div><span className="pink">★</span> {c.reviews.rating.toLocaleString('es-CL')} <span className="google-label">Google</span></div><small>Basado en {c.reviews.count} reseñas en Google</small><p>{c.reviews.invitation}</p></Link></div><div className="review-grid">{c.reviews.items.filter(r=>r.published).map((r,i)=><article className="review" key={i}><div className="stars" aria-label={`${r.stars} de 5 estrellas`}>{'★'.repeat(r.stars)}</div><blockquote>“{r.text}”</blockquote><div className="review-author"><span>{r.name.slice(0,1)}</span><strong>{r.name}</strong></div></article>)}</div></div></section>
<section className="gallery-section"><div className="wrap section"><h2>{c.gallery.title}</h2><p className="section-intro">{c.gallery.subtitle}</p><div className="gallery">{c.gallery.images.map((p,i)=><Picture key={i} {...p}/>)}<Link href={t.instagramUrl} className="instagram-card"><Instagram size={32}/><strong>Ver más en Instagram</strong><span>Síguenos <ArrowRight size={16}/></span></Link></div></div></section>
<section className="wrap section faq" id="faq"><div><h2>{c.faq.title}</h2><p>{c.faq.intro}</p><Link href={wa()} className="text-link pink">Hacer una consulta <ArrowRight size={16}/></Link></div><Accordion type="single" collapsible>{c.faq.items.map((f,i)=><AccordionItem key={i} value={String(i)}><AccordionTrigger className="faq-question">{f.question}</AccordionTrigger><AccordionContent className="faq-answer">{f.answer}</AccordionContent></AccordionItem>)}</Accordion></section>
<section id="contacto" className="contact-section"><div className="wrap section"><h2>{t.title}</h2><p className="section-intro">{t.description}</p><div className="contact-grid"><div><div className="contact-details"><div><MapPin/><p><strong>Dirección</strong>{t.address}, {t.city}</p></div><div><Phone/><p><strong>Contacto</strong><a href={t.phoneUrl}>{t.phone}</a><Link href={wa()}>{t.whatsapp}</Link></p></div><div><Clock/><p><strong>Horario de atención</strong><span className="preserve">{t.hours}</span></p></div></div><div className="actions">{agenda()}<Link href={t.mapsUrl} className="button outline">Abrir en Google Maps</Link></div><div className="request-card"><h3>{t.requestTitle}</h3><p>{t.requestDescription}</p><form onSubmit={send}><label>Tu nombre<input name="owner" required maxLength={120} placeholder="Ej. Camila"/></label><label>Nombre de tu mascota<input name="pet" required maxLength={120} placeholder="Ej. Toby"/></label><label>Tipo de atención<Select value={kind} onValueChange={setKind} required><SelectTrigger className="form-select"><SelectValue placeholder="Selecciona"/></SelectTrigger><SelectContent>{['Consulta veterinaria','Vacunación o control','Peluquería canina','Exámenes o diagnósticos','Otro motivo'].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></label><label>¿Cuándo te acomoda?<Select value={timing} onValueChange={setTiming} required><SelectTrigger className="form-select"><SelectValue placeholder="Selecciona"/></SelectTrigger><SelectContent>{['Lo antes posible','Durante la semana','La próxima semana','Quiero consultar primero'].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></label><button className="button" type="submit"><MessageCircle size={16}/>Solicitar por WhatsApp</button>{error&&<p role="alert">{error}</p>}</form></div></div><iframe title="Ubicación de NanyVet en Concepción" src={t.mapEmbed} loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></div></div></section>
<section className="final-cta"><div className="wrap"><div><h2>{c.footer.title}</h2><p>{c.footer.description}</p></div><div className="cta-actions">{agenda('button white')}{whats('button white-outline')}</div></div></section>
<footer><div className="wrap"><div className="footer-grid"><div><a className="brand footer-brand" href="#inicio">Nany<span>Vet</span></a><p>{c.footer.corporate}</p><div className="social"><Link href={t.facebookUrl} label="Facebook"><Facebook size={20}/></Link><Link href={t.instagramUrl} label="Instagram"><Instagram size={20}/></Link></div></div><div><h3>Contacto</h3><p>{t.address}, {t.city}</p><a href={t.phoneUrl}>{t.phone}</a><Link href={wa()}>{t.whatsapp}</Link><p className="preserve">{t.hours}</p></div><div><h3>Enlaces</h3><Link href={t.agendaUrl}>Agendar hora</Link><Link href={wa()}>Contacto por WhatsApp</Link>{nav.filter(n=>n[1]!=='comunidad').map(([l,id])=><a href={'#'+id} key={id}>{l}</a>)}<a href="#faq">Preguntas frecuentes</a><a href="/admin">Acceso Administrador</a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Clínica Veterinaria NanyVet. Todos los derechos reservados.</span><span>Desarrollado con cuidado para tu mascota.</span></div></div></footer>
<Link href={wa()} label="Hablar por WhatsApp" className={'whatsapp-float '+(scroll>300?'visible':'')}><MessageCircle size={27}/></Link></main>}
