import {z} from 'zod';
const t=z.string().max(20000),u=z.string().max(3000).refine(v=>!v||/^https:\/\//.test(v)||/^\/(?!\/)/.test(v)||/^tel:\+?[\d]+$/.test(v),'URL no válida');
const photo=z.object({src:u,alt:t}),item=z.object({title:t,description:t});
export const schema=z.object({revision:z.number().int().default(4),home:z.object({eyebrow:t,title:t,description:t,microcopy:t,image:photo}),services:z.object({title:t,subtitle:t,items:z.array(item.extend({category:t,message:t})).max(40)}),products:z.object({eyebrow:t,title:t,description:t,items:z.array(item).min(1).max(6),message:t,published:z.boolean().default(true)}),about:z.object({title:t,description:t,doctor:t,quote:t,image:photo,reasonsTitle:t,reasons:z.array(item).length(3)}),process:z.object({title:t,items:z.array(item).max(30)}),reviews:z.object({title:t,subtitle:t,rating:z.number().min(0).max(5),count:z.number().int().min(0),invitation:t,items:z.array(z.object({name:t,text:t,stars:z.number().int().min(1).max(5),published:z.boolean()})).max(100)}),gallery:z.object({title:t,subtitle:t,images:z.array(photo).length(11)}),faq:z.object({title:t,intro:t,items:z.array(z.object({question:t,answer:t,published:z.boolean().default(true)})).max(40)}),contact:z.object({title:t,description:t,address:t,city:t,phone:t,whatsapp:t,hours:t,mapEmbed:u,requestTitle:t,requestDescription:t,phoneUrl:u,whatsappUrl:u,facebookUrl:u,instagramUrl:u,mapsUrl:u,agendaUrl:u,reviewsUrl:u}),footer:z.object({title:t,description:t,corporate:t})});
export type Content=z.infer<typeof schema>;
export const defaults:Content={revision:4,
home:{eyebrow:'Clínica Veterinaria NanyVet · Concepción',title:'Cuidamos a quienes son parte de tu familia.',description:'Atención veterinaria cercana para perros y gatos en Concepción. Consulta con nuestro equipo por atención para otras especies.',microcopy:'Confirma disponibilidad directamente con nuestro equipo.',image:{src:'',alt:'Veterinaria examinando un perro con su tutor en la clínica NanyVet'}},
services:{title:'¿Cómo podemos ayudarte?',subtitle:'Atenciones pensadas para cuidar la salud y bienestar de tu mascota en cada etapa de su vida.',items:[
{category:'Atención clínica',title:'Consultas y medicina interna',description:'Consulta preventiva, medicina interna y control de peso para acompañar la salud de tu mascota.',message:'Hola, quisiera consultar disponibilidad para una consulta preventiva, medicina interna o control de peso.'},
{category:'Prevención',title:'Vacunación y desparasitación',description:'Cuidados preventivos para mantener al día la protección y los controles de perros y gatos.',message:'Hola, quisiera consultar disponibilidad para vacunación o desparasitación.'},
{category:'Procedimientos',title:'Cirugía, hospitalización y rehabilitación',description:'Servicios clínicos para procedimientos, recuperación y seguimiento según evaluación veterinaria.',message:'Hola, quisiera consultar por cirugía, hospitalización o rehabilitación para mi mascota.'},
{category:'Diagnóstico',title:'Exámenes e imagenología',description:'Análisis clínicos, radiografías y ecografías para apoyar la evaluación veterinaria.',message:'Hola, quisiera consultar disponibilidad para análisis clínicos, radiografías o ecografías.'},
{category:'Salud y bienestar',title:'Odontología, nutrición y peluquería',description:'Odontología, alimentación especial y peluquería canina para el cuidado integral de tu mascota.',message:'Hola, quisiera consultar por odontología, alimentación especial o peluquería canina.'}]},
products:{eyebrow:'Todo en un mismo lugar',title:'También encuentras lo que necesita.',description:'Consulta por alimentos, medicamentos y accesorios para acompañar el bienestar de tu mascota.',items:[{title:'Alimentos',description:'Opciones para la alimentación cotidiana o necesidades especiales.'},{title:'Medicamentos',description:'Consulta disponibilidad y orientación para el cuidado indicado.'},{title:'Accesorios',description:'Productos para acompañar su rutina, comodidad y bienestar.'}],message:'Hola, quisiera consultar por disponibilidad de alimentos, medicamentos o accesorios para mi mascota.',published:true},
about:{title:'Una atención cercana empieza por conocer a quien cuida de tu mascota.',description:'En NanyVet creemos que una buena atención veterinaria combina criterio profesional, cercanía y un trato respetuoso con cada mascota y su familia.\n\nBajo el liderazgo de la Dra. Liliana Salazar, buscamos que cada consulta sea también un espacio para escuchar, explicar y acompañar en las decisiones de salud de quienes son parte de tu familia.',doctor:'Dra. Liliana Salazar',quote:'Cercanía para cada paciente y su familia.',image:{src:'',alt:'Retrato de médica veterinaria en clínica NanyVet'},reasonsTitle:'Una atención cercana, clara y profesional.',reasons:[{title:'Cuidado con criterio',description:'Atendemos cada caso con responsabilidad, explicando cada paso de forma clara.'},{title:'Trato humano',description:'Sabemos que cada mascota es parte de una familia. Por eso escuchamos, orientamos y acompañamos.'},{title:'Confianza local',description:'Una clínica veterinaria en Concepción, pensada para entregar cercanía y continuidad en el cuidado.'}]},
process:{title:'Agendar es simple.',items:[{title:'Escríbenos o agenda',description:'Cuéntanos qué necesita tu mascota y coordinamos la atención.'},{title:'Visítanos en la clínica',description:'Te recibimos con una atención cercana, clara y profesional.'},{title:'Recibe orientación',description:'Te explicamos los pasos a seguir para cuidar mejor su salud.'}]},
reviews:{title:'Lo que dicen nuestras familias',subtitle:'Experiencias compartidas por tutores que han confiado en NanyVet.',rating:4.6,count:215,invitation:'¿Nos visitaste? Comparte tu experiencia en Google',items:[{name:'Camila C.',text:'La Dra es muy buena en lo que hace ,te explica todo y el trato a las mascotas es excelente . El precio de las consultas está super bien.',stars:5,published:true},{name:'Patricio C.',text:'Excelente servicio! Dra Liliana es muy acertada. Mis gatas quedan muy tranquilas cuando están con ella.',stars:5,published:true},{name:'Juan R.',text:'Muy buena atención, se nota que les importa de verdad. Fui con mi perro y salió muy tranquilo.',stars:5,published:true}]},
gallery:{title:'Conoce nuestra clínica.',subtitle:'Un espacio pensado para entregar atención y cuidado en un ambiente tranquilo y limpio.',images:Array.from({length:11},()=>({src:'',alt:''}))},
faq:{title:'Preguntas frecuentes',intro:'Resolvemos las dudas más comunes antes de tu visita. Si necesitas orientación adicional, escríbenos por WhatsApp.',items:[{question:'¿Cómo puedo agendar una hora?',answer:'Puedes agendar escribiéndonos por WhatsApp o usando el botón de agendamiento disponible en la página.',published:true},{question:'¿Dónde está ubicada NanyVet?',answer:"Estamos en O'Higgins 115, Concepción. Te invitamos a revisar el mapa en la sección de contacto.",published:true},{question:'¿Qué debo llevar a la consulta?',answer:'Si tu mascota tiene carnet sanitario, exámenes anteriores o antecedentes médicos, tráelos para entregar una atención más completa.',published:true},{question:'¿Atienden perros y gatos?',answer:'Sí, entregamos atención para perros y gatos. Para otras especies, consulta previamente con nuestro equipo por WhatsApp.',published:true},{question:'¿Puedo consultar antes de agendar?',answer:'Sí. Puedes escribir por WhatsApp para recibir orientación inicial y confirmar la atención que necesitas.',published:true},{question:'¿Cuáles son los horarios de atención?',answer:'Atendemos de lunes a viernes de 10:00 a 19:00 hrs, y sábados de 10:30 a 14:00 hrs.',published:true},{question:'¿Qué medios de pago aceptan?',answer:'',published:false},{question:'¿La peluquería canina requiere reserva previa?',answer:'',published:false},{question:'¿Atienden sin hora agendada?',answer:'',published:false}]},
contact:{title:'Encuéntranos en Concepción.',description:'Estamos disponibles para orientarte y ayudarte a coordinar la atención que tu mascota necesita.',address:"O'Higgins 115",city:'Concepción',phone:'+56 41 323 7521',whatsapp:'+56 9 9819 6995 (WhatsApp)',hours:'Lunes a Viernes: 10:00 - 19:00 hrs\nSábados: 10:30 - 14:00 hrs\nDomingos y festivos: Cerrado',mapEmbed:'https://www.google.com/maps?cid=7277369851985987485&output=embed',requestTitle:'Cuéntanos qué necesita tu mascota.',requestDescription:'Al enviar, abriremos WhatsApp con tu solicitud para que puedas confirmarla directamente con NanyVet.',phoneUrl:'tel:+56413237521',whatsappUrl:'https://wa.me/56998196995',facebookUrl:'https://www.facebook.com/Nanyvet',instagramUrl:'https://www.instagram.com/nanyvet_veterinaria/?hl=es-la',mapsUrl:'https://www.google.com/maps?cid=7277369851985987485',agendaUrl:'https://agendapro.com/mp/cl/pl/clinica-veterinaria-nanyvet-concepcion/41087',reviewsUrl:'https://www.google.com/search?q=Cl%C3%ADnica+Veterinaria+Nanyvet#lrd=0x9669b5dbde9cd25d:0x64fe6952bec3079d,1'},
footer:{title:'Cuidamos a tu mascota con responsabilidad y cercanía.',description:'Agenda tu atención de forma directa.',corporate:'Clínica Veterinaria NanyVet ofrece atención médica y peluquería para perros y gatos en Concepción, priorizando un trato cercano, humano y responsable.'}};
